addons:
  apt:
    packages:
      - oracle-java8-installer

language: java
jdk: 
  - oraclejdk8
sudo: false

before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew test
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)