language: java
jdk: 
  - openjdk8
  - openjdk9
  - openjdk11
  - openjdk12
sudo: false

before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew test
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)